"""add users and link owner

Revision ID: eeff38637f12
Revises: 8ec853cd4260
Create Date: 2026-09-28 01:06:07.886260

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeff38637f12"
down_revision: Union[str, Sequence[str], None] = "8ec853cd4260"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("links", sa.Column("owner_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_links_owner_id"), "links", ["owner_id"], unique=False)
    op.create_foreign_key(
        "fk_links_owner_id_users",
        "links",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_links_owner_id_users", "links", type_="foreignkey")
    op.drop_index(op.f("ix_links_owner_id"), table_name="links")
    op.drop_column("links", "owner_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
